name: Boston Transit ETL Upload

on:
  workflow_dispatch:  # Manual run from GitHub UI
  schedule:
    - cron: '0 0 * * *'   # Runs daily at midnight UTC

jobs:
  etl-upload:
    runs-on: ubuntu-latest
    env:
      AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      RDS_USER: ${{ secrets.RDS_USER }}
      RDS_PASS: ${{ secrets.RDS_PASS }}
      RDS_HOST: ${{ secrets.RDS_HOST }}
      RDS_PORT: ${{ secrets.RDS_PORT }}
      RDS_DB: ${{ secrets.RDS_DB }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas boto3 sqlalchemy psycopg2-binary python-dotenv

      - name: Run ETL upload script
        run: |
          python ETL/upload_to_rds.py
